#!/bin/bash
set -e

echo "======================================"
echo "  Als-Dimmer Setup Hook"
echo "======================================"
echo ""

# Environment variables available:
# - MOUNT_POINT: Root filesystem mount point
# - PI_PASSWORD: User password (empty if unchanged)
# - IMAGE_WORK_DIR: Working directory path

echo "Running inside chroot environment"
echo "Building als-dimmer from source..."
echo ""

# Install build dependencies (no-op if already installed)
echo "[1/5] Installing build dependencies..."
apt-get update -qq
apt-get install -y cmake g++ make git libddcutil-dev

# Repo, ref and prefix come from the hook-list line, falling back to the values
# this hook has always used when it is run outside the imager. Taking them from
# the line is what puts als-dimmer's remote head in the apps-stage stamp, so a
# push to als-dimmer re-triggers the build instead of being silently skipped;
# reading them here as well keeps the line and the clone from drifting apart.
ALS_REPO="${HOOK_GIT_REPO:-https://github.com/hackboxguy/als-dimmer.git}"
ALS_REF="${HOOK_GIT_TAG:-main}"
ALS_PREFIX="${HOOK_INSTALL_DEST:-/home/pi/als-dimmer}"

# Clone als-dimmer repository
echo "[2/5] Cloning als-dimmer from GitHub ($ALS_REPO @ $ALS_REF)..."
cd /tmp
git clone --branch "$ALS_REF" "$ALS_REPO" als-dimmer
cd als-dimmer

# Create build directory and configure als-dimmer
echo "[3/5] Configuring CMake..."
mkdir -p build && cd build
cmake -DCMAKE_INSTALL_PREFIX="$ALS_PREFIX" \
      -DCMAKE_BUILD_TYPE=Release \
      -DCONFIG_FILE="config_fpga_opti4001_dimmer800.json" \
      -DUSE_DDCUTIL=ON \
      -DINSTALL_SYSTEMD_SERVICE=ON \
      .. > /dev/null

# Build als-dimmer
echo "[4/5] Building als-dimmer (this may take a few minutes)..."
make -j$(nproc) > /dev/null 2>&1

# Install als-dimmer and 2nd instance(keep 2nd instance linked but dont start)
echo "[5/5] Installing als-dimmer to $ALS_PREFIX..."
make install > /dev/null

# Config selection: als-dimmer is deliberately display-agnostic, so which
# config it runs is decided here, by the display the head unit actually drives.
# Without this a head unit with an OLED panel starts on the FPGA config above
# and logs an I2C write error twice a second, because nothing answers at the
# FPGA's address.
#
# The launcher lives in br-wrapper next to the buildroot packaging of the same
# hook, so there is one copy of it rather than two that drift. Shallow clone,
# take the one file, drop the clone.
echo "[5b/5] Installing the als-dimmer config selector..."
cd /tmp
git clone --depth 1 https://github.com/hackboxguy/br-wrapper.git br-wrapper-sel
install -D -m 0755 /tmp/br-wrapper-sel/package/als-dimmer/als-dimmer-select-config.sh \
        "$ALS_PREFIX"/bin/als-dimmer-select-config.sh
rm -rf /tmp/br-wrapper-sel

# The drop-in is written here rather than copied, because the only thing that
# differs from br-wrapper's copy is the launcher path: buildroot installs to
# /usr/bin, this image to /home/pi/als-dimmer/bin. A drop-in under
# /etc/systemd/system overrides the enabled unit wherever the unit file itself
# lives, which is what makes it work against a /home/pi install.
install -d -m 0755 /etc/systemd/system/als-dimmer.service.d
cat > /etc/systemd/system/als-dimmer.service.d/10-select-config.conf <<DROPIN
# Select the als-dimmer config from the display this head unit actually drives.
# Generated by misc-tools board-configs/micropanel/packages/als-dimmer-hook.sh;
# the launcher it points at is br-wrapper package/als-dimmer/.
# The empty ExecStart= is required by systemd to clear the inherited one before
# setting a replacement.
[Service]
ExecStart=
ExecStart=${ALS_PREFIX}/bin/als-dimmer-select-config.sh
DROPIN

systemctl enable "$ALS_PREFIX"/lib/systemd/system/als-dimmer.service
systemctl link "$ALS_PREFIX"/lib/systemd/system/als-dimmer-pwm.service

#restores last set dual-display mode
systemctl link /home/pi/micropanel/lib/systemd/system/disp-settings-dual-display-restore.service
systemctl enable disp-settings-dual-display-restore.service
################################################

# Cleanup build artifacts and source
echo "Cleaning up build artifacts..."
cd /
rm -rf /tmp/als-dimmer

# NOTE: Build dependencies will be purged by main script
# No apt-get purge here!

echo ""
echo "======================================"
echo "  Als-Dimmer Setup Complete"
echo "======================================"
echo "Installation path: $ALS_PREFIX"
echo "Binaries:"
echo "  - als-dimmer (main daemon)"
echo "  - als-dimmer-select-config.sh (picks the config from the display type)"
echo "Config selection: ots-oled-17 -> config_ioc_opt5001_tcon_ots17.json,"
echo "                  everything else -> config.json (the FPGA default above)"
echo ""
echo "Note: Build deps purged by main script"
echo "======================================"
