#!/bin/bash
set -e

# Media-Mux Setup Hook for custom-pi-imager
#
# Environment variables available:
# - MOUNT_POINT: Root filesystem mount point (not used - we're in chroot)
# - PI_PASSWORD: User password
# - IMAGE_WORK_DIR: Working directory path
# - HOOK_GIT_REPO: Git repository URL (optional, defaults to hackboxguy/media-mux)
# - HOOK_GIT_TAG: Git branch/tag (optional, defaults to dynamic-config)
# - HOOK_INSTALL_DEST: Installation destination (optional, defaults to /home/pi/media-mux)

echo "======================================"
echo "  Media-Mux Setup Hook"
echo "======================================"
echo ""

# Set defaults
REPO_URL="${HOOK_GIT_REPO:-https://github.com/hackboxguy/media-mux.git}"
GIT_REF="${HOOK_GIT_TAG:-dynamic-config}"
INSTALL_DIR="${HOOK_INSTALL_DEST:-/home/pi/media-mux}"
LOG_FILE="/var/log/media-mux-setup.log"

echo "Repository: $REPO_URL"
echo "Git ref: $GIT_REF"
echo "Install directory: $INSTALL_DIR"
echo ""

# Helper functions
log() {
    echo "$1"
    echo "$(date '+%Y-%m-%d %H:%M:%S') $1" >> "$LOG_FILE"
}

log_step() {
    printf "%-55s " "$1"
}

log_ok() {
    echo "[OK]"
    echo "$(date '+%Y-%m-%d %H:%M:%S') [OK] $1" >> "$LOG_FILE"
}

log_fail() {
    echo "[FAIL]"
    echo "$(date '+%Y-%m-%d %H:%M:%S') [FAIL] $1" >> "$LOG_FILE"
}

#------------------------------------------------------------------------------
# Step 1: Clone repository
#------------------------------------------------------------------------------
log_step "[1/8] Cloning media-mux repository..."
rm -rf "$INSTALL_DIR"
git clone --recursive "$REPO_URL" "$INSTALL_DIR" >> "$LOG_FILE" 2>&1
cd "$INSTALL_DIR"
git checkout "$GIT_REF" >> "$LOG_FILE" 2>&1
git submodule update --init --recursive >> "$LOG_FILE" 2>&1
log_ok "clone"

#------------------------------------------------------------------------------
# Step 2: Create autoplay symlink (auto-negotiation mode)
#------------------------------------------------------------------------------
log_step "[2/8] Setting up auto-startup player..."
rm -f "$INSTALL_DIR/media-mux-autoplay.sh" 2>/dev/null
ln -s media-mux-autoplay-master.sh "$INSTALL_DIR/media-mux-autoplay.sh"
log_ok "autoplay symlink"

#------------------------------------------------------------------------------
# Step 3: Configure avahi-publish (placeholder for first-boot)
#------------------------------------------------------------------------------
log_step "[3/8] Configuring avahi-publish service..."
cat > "$INSTALL_DIR/avahi-publish-media-mux.sh" << 'EOF'
#!/bin/sh
# Placeholder - will be regenerated by media-mux-first-boot.sh with MAC-based hostname
MY_ID_STRING="media-mux-auto"
MY_ID_PORT=80
MY_ID_SERVICE="_http._tcp"
MY_ID_HW=$(ifconfig |grep -A1 eth0 |grep inet | awk '{print $2}')
avahi-publish-service -s "$MY_ID_STRING [$MY_ID_HW]" $MY_ID_SERVICE $MY_ID_PORT
EOF
chmod +x "$INSTALL_DIR/avahi-publish-media-mux.sh"
log_ok "avahi-publish"

#------------------------------------------------------------------------------
# Step 4: Create first-boot marker (hostname set on first boot from MAC)
#------------------------------------------------------------------------------
log_step "[4/8] Creating first-boot marker..."
touch "$INSTALL_DIR/.first-boot-pending"
chmod +x "$INSTALL_DIR/media-mux-first-boot.sh"
log_ok "first-boot marker"

#------------------------------------------------------------------------------
# Step 5: Setup rc.local (auto-negotiation mode)
#------------------------------------------------------------------------------
log_step "[5/8] Configuring rc.local startup script..."
cp "$INSTALL_DIR/rc.local.auto" /etc/rc.local
chmod +x /etc/rc.local
log_ok "rc.local"

#------------------------------------------------------------------------------
# Step 6: Compile media-mux-controller
#------------------------------------------------------------------------------
log_step "[6/8] Compiling media-mux-controller..."
gcc "$INSTALL_DIR/media-mux-controller.c" -o "$INSTALL_DIR/media-mux-controller" >> "$LOG_FILE" 2>&1
log_ok "media-mux-controller"

#------------------------------------------------------------------------------
# Step 7: Setup Kodi configuration
#------------------------------------------------------------------------------
log_step "[7/8] Configuring Kodi settings..."
mkdir -p /home/pi/.kodi/userdata
cp "$INSTALL_DIR/sources.xml" /home/pi/.kodi/userdata/ 2>/dev/null || true
cp "$INSTALL_DIR/guisettings.xml" /home/pi/.kodi/userdata/ 2>/dev/null || true
log_ok "Kodi config"

#------------------------------------------------------------------------------
# Step 8: Configure HDMI audio output
#------------------------------------------------------------------------------
log_step "[8/8] Configuring HDMI audio..."
CONFIG_FILE="/boot/firmware/config.txt"
if [ -f "$CONFIG_FILE" ]; then
    if ! grep -q "^hdmi_drive=2" "$CONFIG_FILE" 2>/dev/null; then
        echo "hdmi_drive=2" >> "$CONFIG_FILE"
    fi
fi
# Create PulseAudio config to set HDMI as default sink
mkdir -p /home/pi/.config/pulse
cat > /home/pi/.config/pulse/default.pa << 'PULSE_EOF'
.include /etc/pulse/default.pa
# Set HDMI as default sink for media-mux
set-default-sink alsa_output.platform-fef05700.hdmi.hdmi-stereo
PULSE_EOF
log_ok "HDMI audio"

#------------------------------------------------------------------------------
# Step 9: Install kodisync npm dependencies
#------------------------------------------------------------------------------
log_step "[9/9] Setting up kodisync..."
if [ -d "$INSTALL_DIR/kodisync" ] && [ -f "$INSTALL_DIR/kodisync/package.json" ]; then
    cd "$INSTALL_DIR/kodisync"
    npm --silent install >> "$LOG_FILE" 2>&1
    log_ok "kodisync"
else
    echo "[SKIP] (kodisync not found)"
fi

#------------------------------------------------------------------------------
# Set ownership to pi user (uid:gid 1000:1000)
#------------------------------------------------------------------------------
echo ""
echo "Setting ownership..."
chown -R 1000:1000 "$INSTALL_DIR"
chown -R 1000:1000 /home/pi/.kodi 2>/dev/null || true
chown -R 1000:1000 /home/pi/.config 2>/dev/null || true

#------------------------------------------------------------------------------
# Complete
#------------------------------------------------------------------------------
echo ""
echo "======================================"
echo "  Media-Mux Setup Complete"
echo "======================================"
echo "Mode: AUTO-NEGOTIATION"
echo "Hostname will be generated from MAC address on first boot"
echo "Any device can trigger sync (no fixed master/slave roles)"
echo ""
echo "Installation path: $INSTALL_DIR"
echo "Log file: $LOG_FILE"
echo "======================================"
